version: "3.3"

services:
  graphql-java-kickstart:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    deploy:
      resources:
        limits:
          memory: 320M
        reservations:
          memory: 128M
